services:
    mareg_bootstrap.navbar_renderer:
        # The class implements Knp\Menu\Renderer\RendererInterface
        class: Mareg\Bundle\BootstrapBundle\Menu\Renderer\NavbarRenderer
        arguments: ['@twig', 'MaregBootstrapBundle:Menu:navbar.html.twig'] # set your own dependencies here
        tags:
            - { name: knp_menu.renderer, alias: navbar }

    mareg_bootstrap.menu_builder:
        class: Mareg\Bundle\BootstrapBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        
    mareg_bootstrap.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: mareg_bootstrap.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu